### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Mr-BeanSir** [internetathlete/DingTalk-Live-Playback-Download-Tool#9]
Microsoft Windows [版本 10.0.19045.2965]
(c) Microsoft Corporation。保留所有权利。

F:\dingdown>DingTalk-Live-Playback-Download-Tool.exe
===============================================
     欢迎使用钉钉直播回放下载工具 v1.2
         构建日期：2024年11月10日
===============================================
请选择下载模式（输入1：单个视频下载模式，输入2：批量下载模式，直接回车默认选择1）:
请输入钉钉直播回放分享链接: 
请选择保存模式（输入1：保存到程序默认路径，输入2：手动选择保存路径模式，直接回车默认选择1）:
请选择您使用的浏览器（输入1：Edge，输入2：Chrome，输入3：Firefox，直接回车默认选择1）: 2
获取Cookie时发生错误: Message:

发生错误: name 'browser' is not defined
发生错误: cannot access local variable 'browser' where it is not associated with a value
Traceback (most recent call last):
  File "DingTalk-Live-Playback-Download-Tool.py", line 161, in get_browser_cookie
    if browser:

  File "selenium\webdriver\chrome\webdriver.py", line 45, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 66, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 238, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 325, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 380, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 193, in check_response
selenium.common.exceptions.WebDriverException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DingTalk-Live-Playback-Download-Tool.py", line 346, in single_mode
    if browser:

  File "DingTalk-Live-Playback-Download-Tool.py", line 192, in get_browser_cookie
    try:
       ^
NameError: name 'browser' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DingTalk-Live-Playback-Download-Tool.py", line 463, in <module>
  File "DingTalk-Live-Playback-Download-Tool.py", line 385, in single_mode
    print("未找到包含 'm3u8' 字符的请求链接。")
    ^^^^^^
UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DingTalk-Live-Playback-Download-Tool.py", line 475, in <module>
NameError: name 'browser' is not defined
[PYI-19944:ERROR] Failed to execute script 'DingTalk-Live-Playback-Download-Tool' due to unhandled exception!

F:\dingdown>

**Comment by internetathlete** [comment]
根据错误提示应该是程序中selenium模块在调用浏览器的时候出现了问题
1.请确认您在“选择您使用的浏览器”该步骤中选择的浏览器在您的系统中已安装且能够正常运行
2.尝试安装其他浏览器，并在“选择您使用的浏览器”该步骤中尝试选择其他浏览器
3.可能是selenium在初始化配置webdriver时遇到问题，有可能是网络问题或其他原因，请更换网络再次尝试。
4.经测试本工具目前仍能使用，本人测试环境为 Windows11 24H2 系统 + Edge浏览器

**Comment by Mr-BeanSir** [comment]
解决了，cmd设置了proxy，导致localhost被代理
